### ISSUE TITLE
URL argument must be a string

### ISSUE THREAD

**Issue by Dakota-Brown** [slackapi/template-actionable-notifications#8]
I have my app up and running on Heroku, however, when I post to it, I receive the following error from the app: `"body": "The ticket was not created"`

And this error on the console: `TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined`.

I am sure this is a simple fix, but I am not sure what I am doing wrong. I haven't made any customizations, this is the stock cloned app. This might not be super helpful, I am still learning how to use everything and more than happy to provide more context if needed.

Here is the exact error:
`2020-01-24T18:53:15.765366+00:00 app[web.1]: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
2020-01-24T18:53:15.765383+00:00 app[web.1]:     at validateString (internal/validators.js:112:11)
2020-01-24T18:53:15.765386+00:00 app[web.1]:     at Url.parse (url.js:155:3)
2020-01-24T18:53:15.765388+00:00 app[web.1]:     at Object.urlParse [as parse] (url.js:150:13)
2020-01-24T18:53:15.765391+00:00 app[web.1]:     at dispatchHttpRequest (/app/node_modules/axios/lib/adapters/http.js:67:22)
2020-01-24T18:53:15.765395+00:00 app[web.1]:     at new Promise (<anonymous>)
2020-01-24T18:53:15.765397+00:00 app[web.1]:     at httpAdapter (/app/node_modules/axios/lib/adapters/http.js:20:10)
2020-01-24T18:53:15.765399+00:00 app[web.1]:     at dispatchRequest (/app/node_modules/axios/lib/core/dispatchRequest.js:59:10)
2020-01-24T18:53:15.765401+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:94:5) {
2020-01-24T18:53:15.765403+00:00 app[web.1]:   code: 'ERR_INVALID_ARG_TYPE'
2020-01-24T18:53:15.765405+00:00 app[web.1]: }`

**Comment by Dakota-Brown** [comment]
Stackoverflow post with more information. [Link](https://stackoverflow.com/questions/59903713/getting-an-error-the-url-argument-must-be-of-type-string-received-type-undef)
